#!/usr/bin/env bash
# This script displays username, user ID, and home directory from /etc/passwd

while IFS=':' read -r username password uid gid gecos home shell
do
    echo "$username $uid $home"
done < /etc/passwd
