#!/usr/bin/env bash
# This script displays "Best School" 10 times, with "Hi" after the 9th iteration

counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    
    # Check if this is the 9th iteration
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    
    counter=$(expr $counter + 1)
done
