#!/usr/bin/env bash
#this script showing list of best school but on 4th iteration we has bad luck and on 8 we have good luck"

counter=1
while [ $counter -le 10 ]
do 
	if [ $counter -eq 4 ]
	then 
		echo "bad luck"

	elif [ $counter -eq 8 ]
	then
		echo "good luck"
			
	else 
`                echo "Best School"
	fi
counter=$(expr $counter + 1)
done
