#!/usr/bin/env bash
#This script shows if the file exists,empty, regular or does not exist
file="school"
if [[ -e $file ]]
	then
	echo "$file file exists"

	if [[ -s $file ]]
       	then
	echo "$file file is empty"
	else
	echo "$file file is not empty"
	fi 

	if [[ -f $file ]]
       	then
	echo "$file file is a regular file"
	else
	echo " "
	fi
else 
	echo "school file does not exist"
fi 


