#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely and handles SIGTERM

trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
